# Makefile for the Linux video drivers on sunxi platform.
# 16 Aug 2014, Tyle, <mailto:tyle@allwinnertech.com>
# Rewritten to use lists instead of if-statements.

obj-y += panels.o lcd_source.o default_eink.o \
         dev_disp.o disp_sys_intf.o disp_display.o \
         disp_features.o disp_device.o disp_lcd.o \
         disp_manager.o disp_private.o \
         de_fcc.o de_gsu.o de_hal.o disp_al.o \
         de_peak.o de_rtmx.o de_scaler_table.o\
         de_vep_table.o de_vsu.o de_feat.o \
         de_lcd.o de_lti.o de_fce.o \
         de_ase.o de_bws.o de_enhance.o \
         de_smbl.o de_ccsc.o de_dcsc.o \
         de_wb.o de_clock.o


