obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP4)	+= cyttsp4.o 
cyttsp4-y := b188_sysconfig.o cyttsp4_core.o cyttsp4_mt_common.o cyttsp4_platform.o cyttsp4_i2c.o 
cyttsp4-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP4_MT_A)	+= cyttsp4_mta.o
cyttsp4-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP4_MT_B)	+= cyttsp4_mtb.o
cyttsp4-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP4_BUTTON)	+= cyttsp4_btn.o
cyttsp4-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP4_PROXIMITY)	+= cyttsp4_proximity.o
#cyttsp4-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP4_I2C)	+=cyttsp4_platform.o cyttsp4_i2c.o
